printf "\e[1;32m                                                                           \\n"
printf "           _|                      _|      _|_|  _|                                \\n"
printf " _|_|_|        _|    _|    _|_|    _|    _|      _|    _|_|    _|      _|      _|  \\n"
printf " _|    _|  _|    _|_|    _|_|_|_|  _|  _|_|_|_|  _|  _|    _|  _|      _|      _|  \\n"
printf " _|    _|  _|  _|    _|  _|        _|    _|      _|  _|    _|    _|  _|  _|  _|    \\n"
printf " _|_|_|    _|  _|    _|    _|_|_|  _|    _|      _|    _|_|        _|      _|      \\n"
printf " _|                                                                                \\n"
printf " _|                                                                                \\n"
printf "                                                                                   \\n"
printf " Author: Nobuto NAKAMICHI, Younghwa CHO, Nobuyuki OSHIMA                           \\n"
printf " Date: 25.02.2024                                                                  \\n"
printf " Version: 1.0.0                                                                    \\n"
printf "\e[0m                                                                              \\n"